services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "4001:3306"
    networks:
      base_masivas:
        ipv4_address: 172.18.0.2

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    networks:
      base_masivas:
        ipv4_address: 172.18.0.3
        
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "4003:3306"
    networks:
      base_masivas:
        ipv4_address: 172.18.0.4
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:4000"
    networks:
      base_masivas:
        ipv4_address: 172.18.0.5
  


networks:
  base_masivas:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

